## Artifical Neural Network

In [4]:
# import libraries
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.8.0'

In [5]:
# importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [7]:
# encode the "gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [9]:
# encode country column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [12]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Build the ANN

In [13]:
# initialising the ANN
ann = tf.keras.models.Sequential()

In [14]:
# add the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [15]:
# add second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [17]:
# add the output layer
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

## Training the ANN

In [18]:
# compile the model
ann.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [19]:
# training the ANN on the training set
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5477 - accuracy: 0.7486
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4734 - accuracy: 0.7958
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4536 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4435 - accuracy: 0.7959
Epoch 5/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4367 - accuracy: 0.7980
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4303 - accuracy: 0.8024
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4231 - accuracy: 0.8115
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4135 - accuracy: 0.8216
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4054 - accuracy: 0.8274
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3994 - accura

## Make Predictions & Evaluate


In [20]:
# Predicting the Test set results
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [22]:

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1525   70]
 [ 202  203]]


0.864